### PR TITLE
Testing master and trying to fix errors

### PR DESCRIPTION
**Pull request by kalwalt**
Testing the master branch i found different issues i will try to fix them and make a first working version.

### CODE REVIEW

**Comment by kalwalt** [comment]
with the last commit video start but issues with viewprojection matrix object:

```
Register trackable
play.js?version=0.64:271 
 + START 
arcontroller.compone….js?version=0.64:72 
Start AR
artoolkit.api.js:1201 
Promise {<pending>}
arcontroller.compone….js?version=0.64:83 
got video <video playsinline style=​"position:​ absolute;​ top:​ 50%;​ left:​ 50%;​ width:​ auto;​ height:​ auto;​ min-width:​ 100%;​ min-height:​ 100%;​ background-size:​ cover;​ overflow:​ hidden;​ transform:​ translate(-50%, -50%)​;​ z-index:​ 1;​">​</video>
artoolkit.debug.js:146 
*** Camera Parameter resized from 640, 480. ***
artoolkit.debug.js:146 
Allocated videoFrameSize 307200
artoolkit.debug.js:146 
Pattern detection mode set to 3.
4
litescene.js?version=0.64:30350 
warning: viewprojection matrix contains NaN when enableCamera is used
4
litescene.js?version=0.64:30350 
warning: viewprojection matrix contains NaN when enableCamera is used
arcontroller.compone…js?version=0.64:113 
Register trackable - Pattern
9824
litescene.js?version=0.64:30350 
warning: viewprojection matrix contains NaN when enableCamera is used
play.js?version=0.64:298 
 + FINISH 
```
The player is showing only the mesh nothing else. Needs to understand why.

**Comment by kalwalt** [comment]
It was my fault, it needs to go in the player window (push the button on the right) and after start the play button (button on right top), after that the video stream start ( i can see myself!) tested the **Hiro** marker _but is not detected_. Probably caused by the error i already reported in the comment above:
```
litescene.js?version=0.64:30350 
warning: viewprojection matrix contains NaN when enableCamera is used
```
but could be also caused by some my wrong settings?

**EDIT:** it is detected because i receive in the console:
`saw a trackable with id 8`
but there is an issue with the viewprojection matrix.

**Review by ThorstenBux — APPROVED** [review]

**Comment by ThorstenBux** [comment]
@kalwalt could you fix the conflicts

**Comment by ThorstenBux** [comment]
never mind. I've just fixed and merged it.

**Pull request merged**
